# Generated by Django 3.0.7 on 2020-07-20 08:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imageUrl', models.CharField(max_length=1000, null=True)),
                ('text', models.CharField(max_length=1000, null=True)),
                ('link', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
