# Generated by Django 3.0.7 on 2020-07-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotions',
            name='isPromotion',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
