# Generated by Django 3.0.7 on 2020-07-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='email_address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
