# Generated by Django 3.0.7 on 2020-07-15 04:57

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='products',
            name='tax_amount',
            field=models.FloatField(default=Decimal('0.00'), validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='receipts',
            name='currency',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
