# Generated by Django 3.0.7 on 2020-07-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipts',
            name='signature',
            field=models.CharField(max_length=200000, null=True),
        ),
    ]
