# Generated by Django 3.0.7 on 2020-07-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessManagement', '0002_products_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='unit',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
