# Generated by Django 3.0.8 on 2020-07-16 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('businessManagement', '0003_auto_20200715_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipts',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.CustomerDetails'),
        ),
    ]
