# Generated by Django 3.0.8 on 2020-07-16 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0001_initial'),
        ('businessManagement', '0004_auto_20200716_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userManagement.User'),
        ),
        migrations.AddField(
            model_name='products',
            name='category_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
