# Generated by Django 3.0.8 on 2020-07-16 05:10

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessManagement', '0005_auto_20200716_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='price',
            field=models.FloatField(default=Decimal('0.00'), validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
