# Generated by Django 3.0.8 on 2020-07-20 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessManagement', '0009_auto_20200718_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageUrl', models.CharField(max_length=1000, null=True)),
                ('text', models.CharField(max_length=1000, null=True)),
                ('link', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='receipts',
            name='sellerName',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
