# Generated by Django 3.0.7 on 2020-06-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='issue_no',
            field=models.CharField(max_length=10),
        ),
    ]
