# Generated by Django 3.0.7 on 2020-07-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
